local L = LibStub("AceLocale-3.0"):NewLocale("RangeDisplay", "enUS", true)
if not L then return end
		
L["Locked"] = true
L["Lock/Unlock display frame"] = true
L["Out of range display"] = true
L["Show/Hide display if the target is out of range"] = true
L["Check visibility"] = true
L["If set, the max range to check will be 'visibility range'"] = true
L["Max range only"] = true
L["Show the maximum range only"] = true
L["Font"] = true
L["Default"] = true
L["Font size"] = true
L["Font outline"] = true
L["None"] = true
L["Normal"] = true
L["Thick"] = true
L["Color"] = true
L["Default color"] = true
L["Out of range section"] = true
L["Short range section"] = true
L["Melee range section"] = true
L["Dead zone section"] = true
L["Enable this color section"] = true
L["Range limit"] = true
L["%s loaded. Type /rangedisplay for help"] = true
L["Enemy only"] = true
L["Show range for enemy targets only"] = true
L["Strata"] = true
L["Frame strata"] = true
L["High"] = true
L["Medium"] = true
L["Low"] = true
L["Configure"] = true
L["Bring up GUI configure dialog"] = true
L["Out of range color"] = true
L["Short range color"] = true
L["Melee range color"] = true
L["Dead zone color"] = true
L["Suffix"] = true
L["A free-form suffix to append to the range display when you are in range"] = true
L["Out of range suffix"] = true
L["A free-form suffix to append to the range display when you are out of range"] = true

L["Range Display"] = true
L["Estimated range display"] = true
