local L = LibStub("AceLocale-3.0"):NewLocale("RangeDisplay", "ruRU", false)
if not L then return end
-- Translated by: Argonavt, Swix, StingerSoft
L["Locked"] = "Фиксировать"
L["Lock/Unlock display frame"] = "Фиксировать/освободить фреймы на экране"
L["Range limit"] = "Предел дистанции"
L["Ranges above this are not reported"] = "Дистанция выше указанной не будет выдаватся"
L["Over limit display"] = "Предел отображения"
L["Show/Hide display if the target is further than range limit"] = "Показать/Скрыть если цель дальше чем заданный предел дистанции"
L["Check visibility"] = "Проверка видимости"
L["If set, the max range to check will be 'visibility range'"] = "Если установленно, максималная дистация для проверки будет 'видимая дистанция'"
L["Max range only"] = "Только макс дистанция"
L["Show the maximum range only"] = "Показывать только максимальную дистанцию"
L["Font"] = "Црифт"
L["Default"] = "По умолчанию"
L["Font size"] = "Размер шрифта"
L["Font outline"] = "Контур шрифта"
L["None"] = "Нету"
L["Normal"] = "Обычный"
L["Thick"] = "Толстый"
L["Color"] = "Цвет"
L["Default section"] = "По умолчанию"
L["Out of range section"] = "Вне досягаемости"
L["Medium range section"] = "Средняя дистанция"
L["Short range section"] = "Не долеко"
L["Close range section"] = "В близи"
L["Enable this color section"] = "Включить окраску"
L["Range limit"] = "Предел дистанции"
L["Auto adjust"] = "Авто регулировка"
L["%s loaded. Type /rangedisplay for help"] = "%s загружен. Для помощи введите /rangedisplay"
L["Enemy only"] = "Только враг"
L["Show range for enemy targets only"] = "Показывать дистанцию только до вражеских целей"
L["Strata"] = "Слои"
L["Frame strata"] = "Слои фрейма"
L["High"] = "Высокий"
L["Medium"] = "Средний"
L["Low"] = "Низкий"
L["Configure"] = "Настройка"
L["Bring up GUI configure dialog"] = "Открывает интерфейс настроек"
L["Suffix"] = "Суффикс"
L["A free-form suffix to append to the range display when you are in range"] = "Суффикс, отображаемый на экране в то время, пока цель находится в пределах досягаемости"
L["Over limit suffix"] = "Суффикс \"Вне досягаемости\""
L["A free-form suffix to append to the range display when you are further than range limit"] = "Суффикс, отображаемый на экране в то время, пока цель находится вне зоны досягаемости. (По умолчанию - +)"

L["Range Display"] = "Отображение дистанции"
L["Estimated range display"] = "Отображение предполагаемой дистанции"
L["Enabled"] = "Включен"

L["|cffeda55fLeft Click|r to lock/unlock frames"] = "|cffeda55f[Левый клик]|r фиксирует/освобождает фреймы"
L["|cffeda55fRight Click|r to open the configuration window"] = "|cffeda55f[Правый клик]|r открывает окно настроек"
L["Hide minimap icon"] = "Скрыть иконку у мини карты"

L["RangeDisplay: %s"] = "Отображение дистанции: %s" -- %s will be Target, Focus, etc
L["|cffeda55fControl + Left Click|r to lock frames"] = "|cffeda55f[Control + Левый клик]|r фиксирует фрейм"
L["|cffeda55fDrag|r to move the frame"] = "|cffeda55f[Двигайте]|r для перемещения окна"

L["playertarget"] = "Цель"
L["focus"] = "Фокус"
L["pet"] = "Питомец"
