local L = LibStub("AceLocale-3.0"):NewLocale("RangeDisplay", "zhCN", false)
if not L then return end

--zhCN by lcncg

L["Locked"] = "锁定"
L["Lock/Unlock display frame"] = "锁定或解锁显示框"
L["Out of range display"] = "射程外显示"
L["Show/Hide display if the target is out of range"] = "目标在射程外时是否显示"
L["Check visibility"] = "视线范围"
L["If set, the max range to check will be 'visibility range'"] = "设置后最大射程为视线范围'"
L["Max range only"] = "只显示最大射程"
L["Show the maximum range only"] = "只显示最大射程"
L["Font"] = "字体"
L["Default"] = "默认"
L["Font size"] = "字号"
L["Font outline"] = "字型"
L["None"] = "无"
L["Normal"] = "正常"
L["Thick"] = "加粗"
L["Color"] = "颜色"
L["%s loaded. Type /rangedisplay for help"] = "%s已加载。输入 /rangedisplay 进行设置"
L["Enemy only"] = "仅敌对"
L["Show range for enemy targets only"] = "仅显示敌对目标距离"
L["Strata"] = "层面"
L["Frame strata"] = "框架显示层面"
L["High"] = "最高层"
L["Medium"] = "中间层"
L["Low"] = "最低层"
L["Configure"] = "设置"
L["Bring up GUI configure dialog"] = "打开设置窗口"
L["Out of range color"] = "射程外颜色"
L["Suffix"] = "后缀"
L["A free-form suffix to append to the range display when you are in range"] = "当目标在你的射程内时显示一个后缀"
L["Out of range suffix"] = "射程外后缀"
L["A free-form suffix to append to the range display when you are out of range"] = "当目标在你的射程外时显示一个后缀"

L["Range Display"] = "目标距离"
L["Estimated range display"] = "监视目标距离"
