local L = LibStub("AceLocale-3.0"):NewLocale("RangeDisplay", "koKR", false)
if not L then return end

L["Locked"] = "잠금"
L["Lock/Unlock display frame"] = "화면의 창을 잠그거나 이동시킵니다."
L["Range limit"] = "거리 제한"
L["Ranges above this are not reported"] = "해당된 거리외 알리지 않습니다."
L["Over limit display"] = "표시 제한 초과"
L["Show/Hide display if the target is out of range"] = "목표가 사정 거리 벗어날 때 표시하거나 숨깁니다."
L["Check visibility"] = "눈에 보이는 거리 체크"
L["If set, the max range to check will be 'visibility range'"] = "설정시, 체크할 최대 거리는 '눈에 보이는 거리'입니다."
L["Max range only"] = "최대 거리만"
L["Show the maximum range only"] = "최대 거리만 표시합니다."
L["Font"] = "글꼴"
L["Default"] = "기본값"
L["Font size"] = "글꼴 크기"
L["Font outline"] = "글꼴 외곽선"
L["None"] = "없음"
L["Normal"] = "보통"
L["Thick"] = "굵게"
L["Color"] = "색상"
L["Default section"] = "기본 섹션"
L["Out of range section"] = "서정 거리 밖 섹션"
L["Medium range section"] = "중간 거리 섹션"
L["Short range section"] = "근접 거리 섹션"
L["Close range section"] = "가까운 거리 섹션"
L["Enable this color section"] = "이 색상 섹션을 사용합니다."
L["Range limit"] = "거리 제한"
L["Auto adjust"] = "자동 조절"
L["%s loaded. Type /rangedisplay for help"] = "%s을 불려옵니다. 도움말을 보실려면 /rangedisplay를 입력하세요."
L["Enemy only"] = "적대적 대상만"
L["Show range for enemy targets only"] = "적대적 대상만 거리 표시"
L["Strata"] = "우선순위"
L["Frame strata"] = "창 우선순위"
L["High"] = "높음"
L["Medium"] = "중간"
L["Low"] = "낮음"
L["Configure"] = "설정"
L["Bring up GUI configure dialog"] = "GUI 설정 창을 불려옵니다."
L["Suffix"] = "접미사"
L["A free-form suffix to append to the range display when you are in range"] = "거리에 있을 때 거리 표시에 추가할 자유로운 형태의 접미사"
L["Over limit suffix"] = "제한 초과 접미사"
L["A free-form suffix to append to the range display when you are further than range limit"] = "제한된 거리 밖에 있을 때 거리 표시에 추가할 자유로운 형태의 접미사"

L["Range Display"] = "거리 표시"
L["Estimated range display"] = "예측 거리 표시"
L["Enabled"] = "사용"

L["|cffeda55fLeft Click|r to lock/unlock frames"] = "|cffeda55f좌 클릭|r 창 잠금/이동"
L["|cffeda55fRight Click|r to open the configuration window"] = "|cffeda55f우 클릭|r 설정 창 열기"
L["Hide minimap icon"] = "미니맵 아이콘 숨김"

L["RangeDisplay: %s"] = "RangeDisplay: %s" -- %s will be Target, Focus, etc
L["|cffeda55fControl + Left Click|r to lock frames"] = "|cffeda55fCtrl + 좌 클릭|r 창 잠금"
L["|cffeda55fDrag|r to move the frame"] = "|cffeda55f드래그|r 창 이동"

L["playertarget"] = "대상"
L["focus"] = "주시"
L["pet"] = "소환수"
