local L = LibStub("AceLocale-3.0"):NewLocale("RangeDisplay", "ruRU", false)
if not L then return end

-- ruRU localizations by Argonavt (fixed by Swix).

L["Locked"] = "Закрепить"
L["Lock/Unlock display frame"] = "Закрепить/открепить фреймы на экране"
L["Out of range display"] = "Показывать всегда"
L["Show/Hide display if the target is out of range"] = "Показывать дистанцию до цели, даже если она находится вне зоны досягаемости"
L["Check visibility"] = "Показывать, если вижу"
L["If set, the max range to check will be 'visibility range'"] = "Показывать дистанцию до цели до тех пор, пока её можно видеть"
L["Max range only"] = "Только макс. расстояние"
L["Show the maximum range only"] = "Показывать только максимальное расстояние до цели"
L["Font"] = "Шрифт"
L["Default"] = "По умолчанию"
L["Font size"] = "Размер шрифта"
L["Font outline"] = "Контур шрифта"
L["None"] = "Нет"
L["Normal"] = "Нормальный"
L["Thick"] = "Толстый"
L["Color"] = "Цвет шрифта"
L["%s loaded. Type /rangedisplay for help"] = "%s загружен. Введите /rangedisplay для справки"
L["Enemy only"] = "Только до врагов"
L["Show range for enemy targets only"] = "Показывать расстояние только до вражеских целей"
L["Strata"] = "Слой"
L["Frame strata"] = "При наложении двух фреймов, сверху будет отображаться тот, чей слой будет иметь более высокий приоритет"
L["High"] = "Высокий"
L["Medium"] = "Средний"
L["Low"] = "Низкий"
L["Configure"] = "Настройки"
L["Bring up GUI configure dialog"] = "Показать экран настроек"
L["Out of range color"] = "Цвет \"Вне диапазона\""
L["Suffix"] = "Суффикс"
L["A free-form suffix to append to the range display when you are in range"] = "Суффикс, отображаемый на экране в то время, пока цель находится в пределах досягаемости"
L["Out of range suffix"] = "Суффикс \"Вне диапазона\""
L["A free-form suffix to append to the range display when you are out of range"] = "Суффикс, отображаемый на экране в то время, пока цель находится вне зоны досягаемости. (По умолчанию - +)"
L["Range Display"] = "Range Display"
L["Estimated range display"] = "Estimated range display"
