local L = LibStub("AceLocale-3.0"):NewLocale("RangeDisplay", "zhTW", false)
if not L then return end

-- zhTW by lcncg

L["Locked"] = "鎖定"
L["Lock/Unlock display frame"] = "鎖定或解除鎖定顯示框"
L["Out of range display"] = "射程外顯示"
L["Show/Hide display if the target is out of range"] = "目標在射程外時是否顯示"
L["Check visibility"] = "視線範轉"
L["If set, the max range to check will be 'visibility range'"] = "設置後最大射程為視線範轉"
L["Max range only"] = "只顯示最大射程"
L["Show the maximum range only"] = "只顯示最大射程"
L["Font"] = "字體"
L["Default"] = "默認"
L["Font size"] = "字號"
L["Font outline"] = "字型"
L["None"] = "無"
L["Normal"] = "正常"
L["Thick"] = "加粗"
L["Color"] = "颜色"
L["%s loaded. Type /rangedisplay for help"] = "%s已加載。輸入 /rangedisplay 進行設置"
L["Enemy only"] = "僅敵對"
L["Show range for enemy targets only"] = "僅顯示敵對目標距離"
L["Strata"] = "層面"
L["Frame strata"] = "框架顯示層面"
L["High"] = "最高層"
L["Medium"] = "中間層"
L["Low"] = "最低層"
L["Configure"] = "設置"
L["Bring up GUI configure dialog"] = "打開設置視窗"
L["Out of range color"] = "射程外顏色"
L["Suffix"] = "尾碼"
L["A free-form suffix to append to the range display when you are in range"] = "當目標在你的射程內時顯示一個尾碼"
L["Out of range suffix"] = "射程外尾碼"
L["A free-form suffix to append to the range display when you are out of range"] = "當目標在你的射程外時顯示一個尾碼"

L["Range Display"] = "目標距離"
L["Estimated range display"] = "監視目標距離"
